language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
install:
  - pip install -q Django==$DJANGO
  - pip install coverage
  - pip install -e git://github.com/django-nose/django-nose.git#egg=django-nose
  - pip install -q -e .
  - pip install coveralls
  - pip install alphabet-detector
  - pip install jsonfield
script:
  - python runtests.py
after_success:
  - coveralls
