language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO=1.11
  - DJANGO=2.2
  - DJANGO=3.0
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=2.2
    - python: "3.4"
      env: DJANGO=3.0
    - python: "3.5"
      env: DJANGO=3.0
install:
  - pip install -q Django==$DJANGO
  - pip install coverage
  - pip install -e git://github.com/django-nose/django-nose.git#egg=django-nose
  - pip install -q -e .
  - pip install coveralls
script:
  - python runtests.py
after_success:
  - coveralls
